version: '3'
services:
  postgres:
    container_name: postgres_server
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=intribox
      - POSTGRES_DB=intribox
      - POSTGRES_DATABASE=totalrandompassword
  redis:
    container_name: redis_server
    image: redis:alpine
    ports:
      - 6379:6379