version: '3'

services:
  postgres:
    container_name: postgres_server
    image: postgres:alpine
    networks:
      - app-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=intribox
      - POSTGRES_DB=intribox
      - POSTGRES_PASSWORD=totalrandompassword
  postgres_migration:
    container_name: postgres_migration
    image: migrate/migrate:latest
    restart: on-failure
    networks:
      - app-network
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    command: -source=file:///migrations -verbose -database postgres://intribox:totalrandompassword@postgres:5432/intribox?sslmode=disable up
  redis:
    container_name: redis_server
    image: redis:alpine
    ports:
      - 6379:6379
  localstack: # for s3 testing
    container_name: localstack_dev
    image: localstack/localstack:latest
    ports:
      - 4563-4599:4563-4599
      - 8081:8081
    environment: 
      - SERVICES=s3
    volumes:
      - './.localstack:/tmp/localstack'
networks:
  app-network:
    driver: bridge