version: '3'

services:
  postgres:
    container_name: postgres_server
    image: postgres:alpine
    networks:
      - app-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=intribox
      - POSTGRES_DB=intribox
      - POSTGRES_PASSWORD=totalrandompassword
  postgres_migration:
    container_name: postgres_migration
    image: migrate/migrate:latest
    restart: on-failure
    networks:
      - app-network
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    command: -source=file:///migrations -verbose -database postgres://intribox:totalrandompassword@postgres:5432/intribox?sslmode=disable up
  redis:
    container_name: redis_server
    image: redis:alpine
    ports:
      - 6379:6379
  minio: # for s3 testing
    container_name: minio
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: "DevAccessKey"
      MINIO_SECRET_KEY: "DevSecretKey"
      MINIO_REGION_NAME: "us-east1"
      MINIO_BUCKET: "testbucket"
    ports:
      - "9000:9000"
    command: minio server /data

networks:
  app-network:
    driver: bridge