name: Go

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set up testing environnment
      run: docker-compose -f docker-compose.dev.yml up -d
    
    - name: Installing AWS CLI
      run: |
      sudo apt-get install awscli
      docker ps -a

    - name: Setup localstack
      run: make setupaws

    - name: Test
      run: make test
  golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v2
          with:
            # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
            version: v1.46

            # Optional: working directory, useful for monorepos
            # working-directory: somedir

            # Optional: golangci-lint command line arguments.
            # args: --exclude-use-default

            # Optional: show only new issues if it's a pull request. The default value is `false`.
            # only-new-issues: true

            # Optional: if set to true then the action will use pre-installed Go.
            # skip-go-installation: true

            # Optional: if set to true then the action don't cache or restore ~/go/pkg.
            # skip-pkg-cache: true

            # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
            # skip-build-cache: true

